travis:
  secure:
    BINSTAR_TOKEN: XvXv23h52DTWIy/knE2FVzrH34k86+m2AA97tzMpCwq9AfiQXDVEQ9IlikvvwmX9sKeER97/g9zelL09WFzN2fOHx0wtsv15Hs7DTC+zQr24fKBB9Ugt13ecHDqInqLqElSeBcXaB8piidYNIyx07KSgppbiAWyL5jqPfUsH4b7IAqPoA5nXLcQMMp24Ch9kLNb70x6p57Cv9/nIJ+JTMUlQ8/D6/vWwIMkmw8PBc0w+bkL9W4Oh47TK+II6EAG9Q+mbXYHC4ronvCyuCVKadWZfSFj0AgRnfnO7SKn1gMMxP3PyMCCsZDGxJMgW9UZ5AHNPjW65MD+rrTMygxlvsUhcA+hIPhzPsrZX6aZQ7Rv8D/nbC8Ggmn/FS/Vukj6Q+CFPhaAlFARQhL1WkSdWbuVQ/vSiE3mRWTaM46DgNk2n18r2KFjXwCMBOe5baatWoWF3E4p5SXK42OJOvM+a2We8RKgkr7yh4zcpUecLmWmNco74VYyXbKvOUcuiEb0tPxZyz0zNHiC85/PBlkumyhy1Y3AA/rQIxnbNrzg4CDVOSEoI33AGX2ns+UmSJqhGYlCLGyIqyfcqLakYjGyyF3vU5QFjkG+a1/dHQP/pHTzVh2SyDPrNIAh/qrD+Y8zT/Kp96PJeS0ZrGvY9OYQ2npKEuGjRrnvMD7yhHHNAuag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
