travis:
  secure:
    BINSTAR_TOKEN: R4tkcU/8Qxr8OoSohlkY8lQ9fobIRDYYgI7DOCFuCFb3QJJzCrXFXPUyoME8C6LAx7XAnl+JPJ5fViwPTpko2mzV6ysqRv+mK/7xp7knngd3ynJ5YyO4Ralzak/V9jrz0qdZLnrqa+tItryy1VK3Gx1vY2RTrOq48Xx1LPFAlLT4K5GjYVgdEAnidKU9Eb6/wY2BQ00iOJoyDxXcjp/ft8LAok6AhipnWeeYIxqsDtnNO/sODDUl0dUlc6EA4L2/Xc74C5DsJrk8Lqden7B6PvVG5pfL6Tgg0tOcAM468FWvsg1Q8VYN1GolXtCqZnjm46IRO6ixfzGMj4waO+tnjHcc9wAtjov9MBFgrNqzlHQjZ6noqS76TCXU+Pltj3fqM/yJBAJiY4WQ3Cz5Mv+kT4CgOGyN3uBO57D+xyAGdgcZQ5sL9PwwXfdQTz+P8q4xnNQSVe5GxTINRTaEVq5+pDwk2tGvXXZOtmlMHjgR52xpEzCcc38GX7I3ou8J8RvEdtja3lvGoS/6XxQaw5hmBT/3AXbk51WeVWu2sU3ykWM/ctUeRRO03tecuQ8tJRJ1HeSlK98PKq1DQmXJaG/TLJMVgXNrf7yqD+nRVKlGs+LBcTtc9963F9OQBKDMukgvNCOA8/zBwZ1iupfM33hm2CRXTPthCk33haUeWry92Gc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
